### ISSUE TITLE
Webserver pod in crash loop back off

### ISSUE THREAD

**Issue by bonominijl** [astronomerio/astronomer-ee#111]
Airflow deployment running in `astronomer.cloud`.

The webserver pod for my deployment is failing the liveness probe. I've deployed 6 sample dags and if I delete the webserver pod, a new pod will come up and I can access the UI for a few minutes, if I refresh enough times I get a 503 and the pod crash loops again. 

![screenshot from 2018-08-03 16-09-56](https://user-images.githubusercontent.com/7431155/43663554-ed38d8a2-9737-11e8-871e-42255f1fbd02.png)
`cerebro@cerebral:~/Desktop/astronomer-cloud-test$ sudo kubectl describe pod nebular-neutron-3770-webserver-55ff6ddc57-4lxcn
Name:           nebular-neutron-3770-webserver-55ff6ddc57-4lxcn
Namespace:      astronomer-cloud
Node:           gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln/10.150.0.5
Start Time:     Fri, 03 Aug 2018 15:22:46 -0400
Labels:         component=webserver
                pod-template-hash=1199288713
                release=nebular-neutron-3770
                tier=airflow
                workspace=
Annotations:    <none>
Status:         Running
IP:             10.16.2.3
Controlled By:  ReplicaSet/nebular-neutron-3770-webserver-55ff6ddc57
Containers:
  nebular-neutron-3770-webserver:
    Container ID:  docker://eaa83b3aa8e447726fd3058348a14103827e4d7dd548ae2960047be1abf3bc7c
    Image:         registry.astronomer.cloud/nebular-neutron-3770/airflow:cli-5
    Image ID:      docker-pullable://registry.astronomer.cloud/nebular-neutron-3770/airflow@sha256:a6193b0faf5720279fdebda716dcea3c3d0b2f18be20aa257e2863e58517a1aa
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      airflow
      webserver
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 03 Aug 2018 16:06:36 -0400
      Finished:     Fri, 03 Aug 2018 16:07:06 -0400
    Ready:          False
    Restart Count:  16
    Liveness:       http-get http://:8080/admin/ delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/admin/ delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      AIRFLOW__CORE__EXECUTOR:                    CeleryExecutor
      AIRFLOW__CELERY__DEFAULT_QUEUE:             celery
      AIRFLOW__SCHEDULER__STATSD_ON:              True
      AIRFLOW__SCHEDULER__STATSD_PORT:            9125
      AIRFLOW__SCHEDULER__STATSD_PREFIX:          airflow
      ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION:  15
      AIRFLOW__WEBSERVER__BASE_URL:               nebular-neutron-3770-airflow.astronomer.cloud
      AIRFLOW__SCHEDULER__STATSD_HOST:            nebular-neutron-3770-statsd
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:            <set to the key 'connection' in secret 'nebular-neutron-3770-airflow-metadata'>        Optional: false
      AIRFLOW__CELERY__CELERY_RESULT_BACKEND:     <set to the key 'connection' in secret 'nebular-neutron-3770-airflow-result-backend'>  Optional: false
      AIRFLOW__CELERY__BROKER_URL:                <set to the key 'connection' in secret 'nebular-neutron-3770-broker-url'>              Optional: false
      AIRFLOW__CORE__FERNET_KEY:                  <set to the key 'fernet-key' in secret 'nebular-neutron-3770-fernet-key'>              Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cc6bn (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-cc6bn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cc6bn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From                                                          Message
  ----     ------                 ----                ----                                                          -------
  Normal   Scheduled              47m                 default-scheduler                                             Successfully assigned nebular-neutron-3770-webserver-55ff6ddc57-4lxcn to gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln
  Normal   SuccessfulMountVolume  47m                 kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  MountVolume.SetUp succeeded for volume "default-token-cc6bn"
  Normal   Pulling                47m                 kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  pulling image "registry.astronomer.cloud/nebular-neutron-3770/airflow:cli-5"
  Normal   Pulled                 47m                 kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Successfully pulled image "registry.astronomer.cloud/nebular-neutron-3770/airflow:cli-5"
  Warning  Unhealthy              46m                 kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Liveness probe failed: Get http://10.16.2.3:8080/admin/: dial tcp 10.16.2.3:8080: getsockopt: connection refused
  Warning  Unhealthy              46m                 kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Readiness probe failed: Get http://10.16.2.3:8080/admin/: dial tcp 10.16.2.3:8080: getsockopt: connection refused
  Normal   Started                46m (x2 over 47m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Started container
  Normal   Created                46m (x2 over 47m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Created container
  Warning  Unhealthy              45m (x6 over 46m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Liveness probe failed: Get http://10.16.2.3:8080/admin/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Normal   Killing                45m (x2 over 46m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Killing container with id docker://nebular-neutron-3770-webserver:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled                 45m (x2 over 46m)   kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Container image "registry.astronomer.cloud/nebular-neutron-3770/airflow:cli-5" already present on machine
  Warning  Unhealthy              22m (x49 over 46m)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Readiness probe failed: Get http://10.16.2.3:8080/admin/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff                2m (x130 over 43m)  kubelet, gke-astronomer-cloud-rtgzbz-pool-6011-a106f42f-6pln  Back-off restarting failed container
`

**Comment by vparekh94** [comment]
Per @andscoop : this issue appears to have been caused by the readiness and liveliness probes causing workers to go into spin crashes. The webserver pod is trying to terminate, but it's waiting on the new one to spin up, but the new one keeps failing the liveness/readiness checks so it keeps crashing.


This should be fixed with this:
https://github.com/astronomerio/helm.astronomer.io/commit/2bc89f363c23f917c4dc7972ae98f5b5bdd14e63

Has been deployed to cloud - will be rolled out to current customers accordingly.

**Comment by paolaperaza** [comment]
@andscoop or @schnie - can you guys give an update on this per chance? Got a few cloud 2.0 customers still seeing this issue.

**Comment by schnie** [comment]
We have a fix for the next release, early next week. We'll update cloud with the fix as soon as we get that released.

**Comment by bonominijl** [comment]
@paolaperaza Ping me with any new deployments and I can update them manually.

**Comment by paolaperaza** [comment]
@bonominijl @schnie is this still an issue, or did a platform-wide fix go out with v0.4.1?

**Comment by bonominijl** [comment]
@paolaperaza This will still be an issue for new deployments in cloud. 

We haven't updated Cloud2 to latest as that will cause existing users CLI to break, until they upgrade. We can coordinate that this week, or it may make sense to wait on the next release which could be any day now? @schnie

**Comment by schnie** [comment]
We'll honestly probably be releasing a new version every few days for the next couple weeks. Might make sense to start getting this process started. The good news is that the next few patch releases shouldn't break any APIs or anything so it should be pretty simple to upgrade them as we release.
